FrontFin/mesh-react-native-sdk

examples/react-native-example/package.json, package.json, scripts/build.js, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, yarn.lock
=> feat: Add Semantic Release

LICENSE.md, README.md, examples/react-native-example/App.tsx, examples/react-native-example/package.json, examples/react-native-example/yarn.lock, package.json, src/__tests__/LinkConnect.test.tsx, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/components/LinkConnect.tsx, src/hooks/useSDKCallbacks.ts, src/types/index.ts, yarn.lock
fixes: https://front-finance.atlassian.net/browse/B2B-1533
=> B2 b 1533 accessand transfer destination tokens

README.md, examples/react-native-example/App.tsx, examples/react-native-example/components/reports/index.tsx
fixes: https://front-finance.atlassian.net/browse/B2B-1700
=> B2B-1700 update example app and fix linting issues

.github/workflows/readme.io.yml
fixes: https://front-finance.atlassian.net/browse/B2B-1527
=> B2B-1527 update readme.io notes with release

README.md, examples/react-native-example/package.json, package.json, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/hooks/useSDKCallbacks.ts, src/types/index.ts
=> B2B-1755 extend react native events

examples/react-native-example/yarn.lock, package.json, yarn.lock
fixes: https://front-finance.atlassian.net/browse/SEC-11
fixes: https://front-finance.atlassian.net/browse/SEC-13
fixes: https://front-finance.atlassian.net/browse/SEC-22
=> SEC-11 security patches

examples/react-native-example/App.tsx, examples/react-native-example/package.json, package.json, src/__tests__/LinkConnect.test.tsx, src/__tests__/NavBar.test.tsx, src/__tests__/SDKViewContainer.tsx, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/components/LinkConnect.tsx, src/components/NavBar.tsx, src/components/SDKContainer.styled.ts, src/components/SDKContainer.tsx, src/components/SDKViewContainer.tsx, src/index.ts, src/types/index.ts, yarn.lock
fixes: https://front-finance.atlassian.net/browse/B2B-2539
=> B2B-2539 update rn sdk

examples/react-native-example/package.json, package.json, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/components/LinkConnect.tsx, src/constant.ts
fixes: https://front-finance.atlassian.net/browse/B2B-2684
=> B2B-2684 add whitelist domain support

examples/react-native-example/package.json, package.json, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/constant.ts
=> Added google to allowed URLs for coinbase oauth capcha

README.md, examples/react-native-example/package.json, package.json, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/components/LinkConnect.tsx, src/types/index.ts
https://front-finance.atlassian.net/browse/SCS-225
=> SCS-225 add option to disable domain whitelisting

README.md, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/constant.ts
SCS-304: reverted adding https://link.trustwallet.com
it was allowing trustwallet web page to open in the SDK and then user was not able to see the link any more
=> SCS-304: reverted adding https://link.trustwallet.com

.github/workflows/android.yml, .github/workflows/main.yml, examples/react-native-example/android/app/build.gradle
=> SCS-281: Distribution pipeline for RN Android App, so mesh team members can test

.github/workflows/build-ios.yml, .husky/pre-commit, examples/react-native-example/ios/MeshConnectRNSDK/Info.plist
=> SCS-268 build ios improvements

.github/workflows/android.yml, .github/workflows/main.yml, .github/workflows/mesh-rn-sdk-release.yml, examples/react-native-example/README.md, examples/react-native-example/package.json, examples/react-native-example/yarn.lock, package.json, yarn.lock
https://front-finance.atlassian.net/browse/SCS-245
=> SCS-245 continues watch

examples/react-native-example/ios/MeshConnectRNSDK/Info.plist
https://front-finance.atlassian.net/browse/GROW-254
MM is not opening up on iOS RN.  iOS Privacy settings probably play a factor so adding metamask url to the plist.
=> add metamask to plist

src/types/index.ts
=> SCS-369: RN SDK: Add 'transferInitiated' & 'transferExecuted' event

examples/react-native-example/package.json, package.json, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/types/index.ts
=> SCS-384 TransferNoEligibleAssets event

examples/react-native-example/README.md, examples/react-native-example/scripts/prepare-e2e.js
[SCS-548](https://meshconnectapi.atlassian.net/browse/SCS-548)
Update domain getfront.com -> meshconnect.com
[SCS-548]: https://meshconnectapi.atlassian.net/browse/SCS-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCS-548 Update domain to meshconnect 

examples/react-native-example/package.json, package.json, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/types/index.ts
=> GROW-494 Add verifyWalletRejected and verifyDonePage events

examples/react-native-example/package.json, package.json, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/components/NavBar.tsx
=> GROW-521: Added React import to NavBar component

examples/react-native-example/package.json, package.json, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/types/index.ts
=> GROW-551 add missing events

examples/react-native-example/ios/MeshConnectRNSDK.xcodeproj/project.pbxproj, examples/react-native-example/package.json, package.json, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/constant.ts
=> SCS-730 WHITELISTED_ORIGINS

examples/react-native-example/package.json, package.json, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/components/LinkConnect.tsx, src/constant.ts
=> XPR-563 trustwallet universal link exception

examples/react-native-example/package.json, package.json, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/types/index.ts
=> XPR-749 add refund address

package.json, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/types/index.ts
This pull request includes version updates, test snapshot adjustments, and enhancements to TypeScript interfaces. The most notable changes involve adding new optional properties to the `BrandInfo` interface, modifying the `LinkSettings` interface to generalize the `language` type, and updating the SDK version.
* Updated the package version in `package.json` from `2.1.17` to `2.1.18`.
* Adjusted the `window.meshSdkVersion` in the test snapshot to reflect the new version `2.1.18`.
* Added four new optional properties (`logoLightUrl`, `logoDarkUrl`, `iconLightUrl`, `iconDarkUrl`) to the `BrandInfo` interface in `src/types/index.ts`.
* Updated the `LinkSettings` interface by changing the `language` property type from a union type (`'en' | 'ru'`) to a more flexible `string` type. Removed the …
=> XPR-989 add integration brand info

examples/react-native-example/ios/Podfile.lock, examples/react-native-example/package-lock.json, examples/react-native-example/package.json, examples/react-native-example/yarn.lock, package.json, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, src/components/LinkConnect.tsx, src/constant.ts, src/hooks/useSDKCallbacks.ts, yarn.lock
=> PLAT-860 open coinbase OAuth in external browser

babel.config.js, examples/react-native-example/package.json, package.json, src/__tests__/__snapshots__/LinkConnect.test.tsx.snap, yarn.lock
=> XPR-1510 patch management
